# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75091f7bd75fee42b92f2d5ceb230add5d5b00fc8dbc787a72d93b624e2062c93a5bc4311158506994bce7ce4f0a292345afa8dd2e02c3ebebc3832528272647

test:
  secret_key_base: e39a766a005fc20f92e5c0be262c5869938d004a23b033e5fc7663c62110ff0bc50a815cc4cb6ea8fa2172ea70898be95516f0d920d551805395e92012757263

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
